In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
#Sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
#Define the vocabulary size
voc_size=10000
#One Hot Representation 
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7315, 2572, 9684, 8724],
 [7315, 2572, 9684, 2111],
 [7315, 3504, 9684, 740],
 [6568, 4444, 3073, 1219, 9174],
 [6568, 4444, 3073, 1219, 2977],
 [8053, 7315, 784, 9684, 9622],
 [7029, 3834, 114, 1219]]

In [11]:
#Word Embedding Representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np 

In [24]:
sent_length=8
embedding_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedding_doc

array([[   0,    0,    0,    0, 7315, 2572, 9684, 8724],
       [   0,    0,    0,    0, 7315, 2572, 9684, 2111],
       [   0,    0,    0,    0, 7315, 3504, 9684,  740],
       [   0,    0,    0, 6568, 4444, 3073, 1219, 9174],
       [   0,    0,    0, 6568, 4444, 3073, 1219, 2977],
       [   0,    0,    0, 8053, 7315,  784, 9684, 9622],
       [   0,    0,    0,    0, 7029, 3834,  114, 1219]])

In [25]:
#feature representation 
dim=10

In [26]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [27]:
model.predict(embedding_doc)

1/1 [==============================] - 0s 90ms/step


array([[[-0.04995392,  0.02776304, -0.02309115,  0.00085126,
         -0.0275683 , -0.04763616, -0.01012208,  0.01204833,
         -0.01663598, -0.01675863],
        [-0.04995392,  0.02776304, -0.02309115,  0.00085126,
         -0.0275683 , -0.04763616, -0.01012208,  0.01204833,
         -0.01663598, -0.01675863],
        [-0.04995392,  0.02776304, -0.02309115,  0.00085126,
         -0.0275683 , -0.04763616, -0.01012208,  0.01204833,
         -0.01663598, -0.01675863],
        [-0.04995392,  0.02776304, -0.02309115,  0.00085126,
         -0.0275683 , -0.04763616, -0.01012208,  0.01204833,
         -0.01663598, -0.01675863],
        [-0.00225226, -0.03999654,  0.02044647, -0.02556984,
          0.02538848, -0.01037786, -0.0452705 ,  0.01921869,
         -0.0321046 ,  0.04179344],
        [-0.0439943 , -0.02261828, -0.03493183, -0.03545562,
          0.01071838, -0.03203908, -0.02221897, -0.01673424,
          0.00598085,  0.01372996],
        [-0.01619493, -0.03874205, -0.01382954,  0.0

In [21]:
embedding_doc[0]

array([   0,    0,    0,    0, 7315, 2572, 9684, 8724])

In [28]:
model.predict(embedding_doc[0])

1/1 [==============================] - 0s 122ms/step


array([[-0.04995392,  0.02776304, -0.02309115,  0.00085126, -0.0275683 ,
        -0.04763616, -0.01012208,  0.01204833, -0.01663598, -0.01675863],
       [-0.04995392,  0.02776304, -0.02309115,  0.00085126, -0.0275683 ,
        -0.04763616, -0.01012208,  0.01204833, -0.01663598, -0.01675863],
       [-0.04995392,  0.02776304, -0.02309115,  0.00085126, -0.0275683 ,
        -0.04763616, -0.01012208,  0.01204833, -0.01663598, -0.01675863],
       [-0.04995392,  0.02776304, -0.02309115,  0.00085126, -0.0275683 ,
        -0.04763616, -0.01012208,  0.01204833, -0.01663598, -0.01675863],
       [-0.00225226, -0.03999654,  0.02044647, -0.02556984,  0.02538848,
        -0.01037786, -0.0452705 ,  0.01921869, -0.0321046 ,  0.04179344],
       [-0.0439943 , -0.02261828, -0.03493183, -0.03545562,  0.01071838,
        -0.03203908, -0.02221897, -0.01673424,  0.00598085,  0.01372996],
       [-0.01619493, -0.03874205, -0.01382954,  0.01141331, -0.04540545,
         0.0176344 , -0.04003919, -0.03776813